Se agrega CD para testing.yml
juanmatiasg/Proyecto_Final pull request #6
Opened 2023-08-21 19:07 UTC by pableArg

Se agre CD para reporte de test

2023-08-21 21:13 UTC, vao-source-code approved these changes, later dismissed

2023-08-21 21:14 UTC, vao-source-code submitted a review, later dismissed

2023-08-21 21:16 UTC, juanmatiasg commented on .github/workflows/ci.yml
> -    branches: []
Porque eliminamo el branches

2023-08-21 21:16 UTC, pableArg commented on .github/workflows/ci.yml
> -    branches: []
Eliminamos esto po rque no hace falta

2023-08-21 21:17 UTC, juanmatiasg approved these changes, later dismissed

2023-08-26 14:36 UTC, vao-source-code requested changes
Aprobado

2023-08-26 14:36 UTC, vao-source-code submitted a review, later dismissed

2023-08-27 15:37 UTC, vao-source-code approved these changes

2023-08-27 15:42 UTC, merged